# Generated by Django 5.2.6 on 2026-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='records_scraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='speed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='uptime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
