# Generated by Django 5.2.6 on 2026-03-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='post',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.blogpost'),
        ),
        migrations.RenameField(
            model_name='blogimage',
            old_name='post',
            new_name='blog',
        ),
    ]
