# Generated by Django 5.2.6 on 2026-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool'), ('Database', 'Database')], default='Tool', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fas fa-code', help_text='FontAwesome class, e.g. fab fa-python', max_length=50),
        ),
    ]
