# Generated by Django 5.2.6 on 2026-02-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_category_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool'), ('Database', 'Database'), ('Soft Skills', 'Soft Skills')], default='Tool', max_length=50),
        ),
    ]
