# Generated by Django 5.2.6 on 2026-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for tools or frameworks'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool'), ('Database', 'Database'), ('Soft Skill', 'Soft Skill')], default='Tool', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-code', help_text='FontAwesome class (example: fab fa-python)', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, help_text='Skill level 1–100 (used for languages & soft skills)', null=True),
        ),
    ]
